version: "2"
services:
  app:
    build: .
    working_dir: /usr/src/workspace
    volumes:
      - ./:/usr/src/workspace
    environment:
      ENVIRONMENT: develop
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    ports:
      - 3000:3000
    links:
      - db

  db:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
